language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

before_install: gem install bundler

rvm:
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-9.1.5.0
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: jruby-head
    - rvm: rbx
  fast_finish: true
