language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

after_success:
  - bundle exec rake test:accuracy
  - bundle exec rake benchmark:memory

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-9.1.5.0
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx
  fast_finish: true
