language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

before_install: gem install bundler

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-9.1.10.0
  - jruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.10.0
    - rvm: jruby-head
    - rvm: rbx
  fast_finish: true
