language: ruby
script:   bundle exec rake
cache:    bundler
sudo:     false

before_install: gem install bundler -v 1.17.3

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.5.5
  - 2.6.3
  - ruby-head
  - jruby-9.2.7.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.7.0
    - rvm: jruby-head
  fast_finish: true
